2025-02-26 20:02:14,859 - INFO - Пользователь 962283941 запустил бота
2025-02-26 20:02:45,631 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/39eELebV1lynYdX9qX4bpd?si=4ddd016f44174283
2025-02-26 20:02:45,632 - INFO - User authentication requires interaction with your web browser. Once you enter your credentials and give authorization, you will be redirected to a url.  Paste that url you were directed to to complete the authorization.
2025-02-26 20:02:45,739 - INFO - Opened https://accounts.spotify.com/authorize?client_id=905ff1dd336242ebb93b247739dfd08c&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8888%2Fcallback&scope=playlist-read-private+playlist-read-collaborative in your browser
2025-02-26 20:05:17,664 - INFO - Пользователь 962283941 запустил бота
2025-02-26 20:34:15,406 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/5XvK5XqQhxvb2SXzTnBtys?si=f6fa791797464383
2025-02-26 20:47:14,777 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024667063F50>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-26 20:47:20,056 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002102FE7C0D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-26 20:47:23,015 - INFO - Пользователь 962283941 запустил бота
2025-02-26 20:47:26,956 - INFO - Пользователь 962283941 запросил авторизацию Spotify
2025-02-26 20:47:51,543 - ERROR - Ошибка авторизации для 962283941: error: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/api/token</code> from this server.</h2>
<h2></h2>
</body></html>
, error_description: None
2025-02-26 20:48:04,350 - INFO - Пользователь 962283941 успешно авторизовался в Spotify
2025-02-26 20:48:32,627 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/23OIV8qtyNO1lVWzcw6xAk?si=6ddb7adadbf64095
2025-02-26 20:48:50,169 - INFO - Успешно отправлен: snowfall для 962283941
2025-02-26 20:49:01,183 - INFO - Успешно отправлен: Last Christmas для 962283941
2025-02-26 20:49:01,425 - INFO - Завершена обработка Мой плейлист № 4 для 962283941
2025-02-26 20:54:10,659 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 20:54:41,829 - INFO - Пользователь 5516363342 запросил авторизацию Spotify
2025-02-26 20:57:53,699 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getUpdates?offset=488892882&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E626144390>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-26 21:00:10,820 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024F6536C0D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-26 21:00:45,375 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000207C5C6C0D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-26 21:00:49,640 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:00:52,608 - INFO - Пользователь 5516363342 запросил авторизацию Spotify
2025-02-26 21:00:55,313 - ERROR - Ошибка авторизации для 5516363342: error: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/api/token</code> from this server.</h2>
<h2></h2>
</body></html>
, error_description: None
2025-02-26 21:01:19,973 - ERROR - Ошибка авторизации для 5516363342: error: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/api/token</code> from this server.</h2>
<h2></h2>
</body></html>
, error_description: None
2025-02-26 21:02:30,418 - INFO - Пользователь 962283941 запросил авторизацию Spotify
2025-02-26 21:02:56,673 - INFO - Пользователь 962283941 успешно авторизовался в Spotify
2025-02-26 21:03:05,307 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/23OIV8qtyNO1lVWzcw6xAk?si=4825994dfda14e23
2025-02-26 21:03:16,922 - INFO - Успешно отправлен: snowfall для 962283941
2025-02-26 21:03:27,572 - INFO - Успешно отправлен: Last Christmas для 962283941
2025-02-26 21:03:27,716 - INFO - Завершена обработка zxczxczx для 962283941
2025-02-26 21:03:47,939 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:03:50,168 - INFO - Пользователь 5516363342 запросил авторизацию Spotify
2025-02-26 21:04:03,521 - INFO - Пользователь 5516363342 успешно авторизовался в Spotify
2025-02-26 21:05:02,468 - INFO - Пользователь 5516363342 отправил плейлист: https://open.spotify.com/playlist/2nGTA5IygCneardNJAvrue
2025-02-26 21:05:02,743 - ERROR - HTTP Error for GET to https://api.spotify.com/v1/playlists/2nGTA5IygCneardNJAvrue with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 403 due to Check settings on developer.spotify.com/dashboard, the user may not be registered.
2025-02-26 21:08:49,577 - INFO - Пользователь 5516363342 отправил плейлист: https://open.spotify.com/playlist/2nGTA5IygCneardNJAvrue
2025-02-26 21:08:49,855 - ERROR - HTTP Error for GET to https://api.spotify.com/v1/playlists/2nGTA5IygCneardNJAvrue with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 403 due to Check settings on developer.spotify.com/dashboard, the user may not be registered.
2025-02-26 21:08:51,406 - INFO - Пользователь 5516363342 запросил авторизацию Spotify
2025-02-26 21:09:13,631 - INFO - Пользователь 5516363342 успешно авторизовался в Spotify
2025-02-26 21:09:19,410 - INFO - Пользователь 5516363342 отправил плейлист: https://open.spotify.com/playlist/2nGTA5IygCneardNJAvrue
2025-02-26 21:09:19,707 - ERROR - HTTP Error for GET to https://api.spotify.com/v1/playlists/2nGTA5IygCneardNJAvrue with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 403 due to Check settings on developer.spotify.com/dashboard, the user may not be registered.
2025-02-26 21:09:27,105 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:09:28,369 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:09:29,449 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:09:32,431 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:09:33,751 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:09:34,172 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:09:34,886 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:09:35,757 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:09:36,385 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:09:36,970 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:09:37,445 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:09:37,888 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:10:21,353 - INFO - Пользователь 5516363342 запросил авторизацию Spotify
2025-02-26 21:10:27,493 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:10:27,608 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:10:27,645 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:10:27,803 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:10:28,109 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:10:28,131 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:10:28,368 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:10:28,463 - INFO - Пользователь 5516363342 запустил бота
2025-02-26 21:11:19,641 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getUpdates?offset=488892921&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001B48AC44210>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-26 21:15:35,642 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000205F586C0D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-26 21:15:58,734 - INFO - Пользователь 5516363342 запросил авторизацию Spotify
2025-02-26 21:16:12,772 - INFO - Пользователь 962283941 запустил бота
2025-02-26 21:16:29,140 - ERROR - Ошибка авторизации для 5516363342: error: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/api/token</code> from this server.</h2>
<h2></h2>
</body></html>
, error_description: None
2025-02-26 21:16:32,342 - ERROR - Ошибка авторизации для 5516363342: error: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/api/token</code> from this server.</h2>
<h2></h2>
</body></html>
, error_description: None
2025-02-26 21:16:58,043 - INFO - Пользователь 5516363342 запросил авторизацию Spotify
2025-02-26 21:16:59,933 - INFO - Пользователь 5516363342 успешно авторизовался в Spotify
2025-02-26 21:17:12,677 - INFO - Пользователь 5516363342 отправил плейлист: https://open.spotify.com/playlist/2nGTA5IygCneardNJAvrue
2025-02-26 21:17:24,051 - INFO - Успешно отправлен: Premonition для 5516363342
2025-02-26 21:17:29,829 - ERROR - Ошибка скачивания DARK SOULS \u2162 для 5516363342: [0;31mERROR:[0m unable to download video data: HTTP Error 403: Forbidden
2025-02-26 21:17:39,905 - INFO - Успешно отправлен: Prologue для 5516363342
2025-02-26 21:17:51,852 - INFO - Успешно отправлен: Firelink Shrine для 5516363342
2025-02-26 21:18:03,187 - INFO - Успешно отправлен: Iudex Gundyr для 5516363342
2025-02-26 21:18:13,726 - INFO - Успешно отправлен: Vordt of the Boreal Valley для 5516363342
2025-02-26 21:18:26,575 - INFO - Успешно отправлен: Curse-rotted Greatwood для 5516363342
2025-02-26 21:18:37,857 - INFO - Успешно отправлен: Crystal Sages для 5516363342
2025-02-26 21:18:48,506 - INFO - Успешно отправлен: Deacons of the Deep для 5516363342
2025-02-26 21:19:01,726 - INFO - Успешно отправлен: High Lord Wolnir для 5516363342
2025-02-26 21:19:12,471 - INFO - Успешно отправлен: Pontiff Sulyvahn для 5516363342
2025-02-26 21:19:54,878 - INFO - Успешно отправлен: Dancer of the Boreal Valley для 5516363342
2025-02-26 21:20:07,513 - INFO - Успешно отправлен: Dragonslayer Armour для 5516363342
2025-02-26 21:20:17,810 - INFO - Успешно отправлен: Old Demon King для 5516363342
2025-02-26 21:20:27,590 - INFO - Успешно отправлен: Oceiros, the Consumed King для 5516363342
2025-02-26 21:20:37,166 - INFO - Успешно отправлен: Ancient Wyvern для 5516363342
2025-02-26 21:20:46,657 - INFO - Успешно отправлен: Nameless King для 5516363342
2025-02-26 21:20:58,112 - INFO - Успешно отправлен: Abyss Watchers для 5516363342
2025-02-26 21:21:08,671 - INFO - Успешно отправлен: Yhorm the Giant для 5516363342
2025-02-26 21:21:27,641 - INFO - Успешно отправлен: Aldritch, Devourer of Gods для 5516363342
2025-02-26 21:21:37,318 - INFO - Успешно отправлен: Twin Princes для 5516363342
2025-02-26 21:21:51,444 - INFO - Успешно отправлен: Soul of Cinder для 5516363342
2025-02-26 21:23:07,788 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/sendMessage?chat_id=5516363342&text=%E2%9D%8C+%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B0%3A+HTTPSConnectionPool%28host%3D%27api.telegram.org%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fbot7954171512%3AAAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA%2FsendMessage%3Fchat_id%3D5516363342%26text%3D%25E2%259A%25A0%25EF%25B8%258F%2B%25D0%259E%25D1%2588%25D0%25B8%25D0%25B1%25D0%25BA%25D0%25B0%2B%25D0%25BF%25D1%2580%25D0%25B8%2B%25D1%2581%25D0%25BA%25D0%25B0%25D1%2587%25D0%25B8%25D0%25B2%25D0%25B0%25D0%25BD%25D0%25B8%25D0%25B8%2B%252ASecret%2BBetrayal%252A%253A%2BA%2Brequest%2Bto%2Bthe%2BTelegram%2BAPI%2Bwas%2Bunsuccessful.%2BError%2Bcode%253A%2B413.%2BDescription%253A%2BRequest%2BEntity%2BToo%2BLarge+%28Caused+by+NameResolutionError%28%22%3Curllib3.connection.HTTPSConnection+object+at+0x0000024EE9E87510%3E%3A+Failed+to+resolve+%27api.telegram.org%27+%28%5BErrno+11001%5D+getaddrinfo+failed%29%22%29%29&reply_parameters=%7B%22message_id%22%3A+275%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024EEA6B0C10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-26 21:27:26,616 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000015DC3463E10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-26 21:27:36,886 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000254C4163E10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-26 21:27:39,643 - INFO - Пользователь 962283941 запросил авторизацию Spotify
2025-02-26 21:27:58,586 - INFO - Пользователь 962283941 успешно авторизовался в Spotify
2025-02-26 21:28:18,441 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/5l779YYwmmJw341SlR6Fyq?si=daff438f66fb4940
2025-02-26 21:28:18,762 - ERROR - HTTP Error for GET to https://api.spotify.com/v1/playlists/5l779YYwmmJw341SlR6Fyq with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 403 due to 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/v1/playlists/5l779YYwmmJw341SlR6Fyq</code> from this server.</h2>
<h2></h2>
</body></html>

2025-02-26 21:28:25,973 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/39eELebV1lynYdX9qX4bpd?si=297edd4c8e774448
2025-02-26 21:28:26,294 - ERROR - HTTP Error for GET to https://api.spotify.com/v1/playlists/39eELebV1lynYdX9qX4bpd with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 403 due to 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/v1/playlists/39eELebV1lynYdX9qX4bpd</code> from this server.</h2>
<h2></h2>
</body></html>

2025-02-26 21:28:30,106 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/39eELebV1lynYdX9qX4bpd?si=297edd4c8e774448
2025-02-26 21:28:30,110 - WARNING - Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FFA2CA5C10>: Failed to resolve 'api.spotify.com' ([Errno 11004] getaddrinfo failed)")': /v1/playlists/39eELebV1lynYdX9qX4bpd?additional_types=track
2025-02-26 21:28:30,711 - WARNING - Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FFA2CA6090>: Failed to resolve 'api.spotify.com' ([Errno 11004] getaddrinfo failed)")': /v1/playlists/39eELebV1lynYdX9qX4bpd?additional_types=track
2025-02-26 21:28:31,912 - WARNING - Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FFA2CA66D0>: Failed to resolve 'api.spotify.com' ([Errno 11004] getaddrinfo failed)")': /v1/playlists/39eELebV1lynYdX9qX4bpd?additional_types=track
2025-02-26 21:28:46,376 - INFO - Успешно отправлен: Runnin' Thru the 7th with My Woadies для 962283941
2025-02-26 21:28:57,690 - INFO - Успешно отправлен: Going Under для 962283941
2025-02-26 21:29:06,892 - INFO - Успешно отправлен: 500lbs для 962283941
2025-02-26 21:29:17,082 - INFO - Успешно отправлен: Sleep Forever для 962283941
2025-02-26 21:29:25,445 - INFO - Успешно отправлен: wldnt get it для 962283941
2025-02-26 21:29:33,490 - INFO - Успешно отправлен: lightz для 962283941
2025-02-26 21:29:43,637 - INFO - Успешно отправлен: Breathe для 962283941
2025-02-26 21:29:51,960 - INFO - Успешно отправлен: GoHardHuh для 962283941
2025-02-26 21:30:01,169 - INFO - Успешно отправлен: The Light at the End of the Tunnel for $9.99 a Month для 962283941
2025-02-26 21:30:10,982 - INFO - Успешно отправлен: HILARIOUS (feat. Cochise) для 962283941
2025-02-26 21:30:19,889 - INFO - Успешно отправлен: Love Game для 962283941
2025-02-26 21:30:30,528 - INFO - Успешно отправлен: Kerosene для 962283941
2025-02-26 21:30:43,546 - INFO - Успешно отправлен: sdp interlude для 962283941
2025-02-26 21:30:53,111 - INFO - Успешно отправлен: Hoes Come Easy для 962283941
2025-02-26 21:30:54,944 - ERROR - Ошибка скачивания trip city для 962283941: [Errno 2] No such file or directory: 'downloads/trip city - lloveglo.mp3'
2025-02-26 21:31:04,321 - INFO - Успешно отправлен: Fade Away для 962283941
2025-02-26 21:31:15,223 - INFO - Успешно отправлен: help_urself 2 для 962283941
2025-02-26 21:31:23,790 - INFO - Успешно отправлен: Black Blood! для 962283941
2025-02-26 21:31:34,305 - INFO - Успешно отправлен: I Wonder для 962283941
2025-02-26 21:31:44,142 - ERROR - Ошибка скачивания MyOwnPersonalHell для 962283941: [0;31mERROR:[0m Postprocessing: audio conversion failed: Exiting normally, received signal 2.
2025-02-27 17:21:14,125 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001A348063F10>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-27 17:21:29,578 - INFO - Пользователь 962283941 запустил бота
2025-02-27 17:21:32,090 - INFO - Пользователь 962283941 запросил авторизацию Spotify
2025-02-27 17:21:40,855 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/23OIV8qtyNO1lVWzcw6xAk?si=bd50057463a740cb
2025-02-27 17:21:40,856 - INFO - User authentication requires interaction with your web browser. Once you enter your credentials and give authorization, you will be redirected to a url.  Paste that url you were directed to to complete the authorization.
2025-02-27 17:21:40,962 - INFO - Opened https://accounts.spotify.com/authorize?client_id=905ff1dd336242ebb93b247739dfd08c&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8888%2Fcallback&scope=playlist-read-private+playlist-read-collaborative+user-read-private+user-read-email in your browser
2025-02-27 17:21:55,186 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/23OIV8qtyNO1lVWzcw6xAk?si=bd50057463a740cb
2025-02-27 17:21:55,186 - INFO - User authentication requires interaction with your web browser. Once you enter your credentials and give authorization, you will be redirected to a url.  Paste that url you were directed to to complete the authorization.
2025-02-27 17:21:55,203 - INFO - Opened https://accounts.spotify.com/authorize?client_id=905ff1dd336242ebb93b247739dfd08c&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8888%2Fcallback&scope=playlist-read-private+playlist-read-collaborative+user-read-private+user-read-email in your browser
2025-02-27 17:22:13,727 - INFO - Успешно отправлен: snowfall для 962283941
2025-02-27 17:22:24,519 - INFO - Успешно отправлен: Last Christmas для 962283941
2025-02-27 17:22:24,687 - INFO - Завершена обработка zxczxczx для 962283941
2025-02-27 17:22:42,029 - INFO - Пользователь 962283941 запустил бота
2025-02-27 17:22:44,418 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/23OIV8qtyNO1lVWzcw6xAk?si=bd50057463a740cb
2025-02-27 17:22:56,485 - INFO - Успешно отправлен: snowfall для 962283941
2025-02-27 17:23:11,021 - INFO - Успешно отправлен: Last Christmas для 962283941
2025-02-27 17:23:11,212 - INFO - Завершена обработка zxczxczx для 962283941
2025-02-27 17:23:21,376 - INFO - Пользователь 570811009 запустил бота
2025-02-27 17:23:49,190 - INFO - Пользователь 570811009 отправил плейлист: https://open.spotify.com/playlist/23OIV8qtyNO1lVWzcw6xAk?si=bd50057463a740cb
2025-02-27 17:23:49,190 - INFO - User authentication requires interaction with your web browser. Once you enter your credentials and give authorization, you will be redirected to a url.  Paste that url you were directed to to complete the authorization.
2025-02-27 17:23:49,209 - INFO - Opened https://accounts.spotify.com/authorize?client_id=905ff1dd336242ebb93b247739dfd08c&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8888%2Fcallback&scope=playlist-read-private+playlist-read-collaborative+user-read-private+user-read-email in your browser
2025-02-27 17:23:49,704 - ERROR - Ошибка обработки плейлиста для 962283941: Server listening on localhost has not been accessed
2025-02-27 17:24:02,152 - INFO - Успешно отправлен: snowfall для 570811009
2025-02-27 17:24:15,235 - INFO - Успешно отправлен: Last Christmas для 570811009
2025-02-27 17:24:15,375 - INFO - Завершена обработка zxczxczx для 570811009
2025-02-27 17:38:20,461 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E86C9782D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-27 17:38:32,155 - INFO - Пользователь 962283941 запустил бота
2025-02-27 17:38:38,795 - INFO - Пользователь 962283941 установил качество 320 kbps
2025-02-27 17:40:10,931 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/5wcnZAy994fsXIesOO3guz?si=b4e840c037054860
2025-02-27 17:40:11,184 - ERROR - HTTP Error for GET to https://api.spotify.com/v1/playlists/5wcnZAy994fsXIesOO3guz with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 403 due to 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/v1/playlists/5wcnZAy994fsXIesOO3guz</code> from this server.</h2>
<h2></h2>
</body></html>

2025-02-27 17:40:13,836 - INFO - Пользователь 962283941 запросил авторизацию Spotify
2025-02-27 17:40:30,113 - INFO - Пользователь 962283941 успешно авторизовался в Spotify
2025-02-27 17:40:36,427 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/5wcnZAy994fsXIesOO3guz?si=b4e840c037054860
2025-02-27 17:40:36,670 - ERROR - HTTP Error for GET to https://api.spotify.com/v1/playlists/5wcnZAy994fsXIesOO3guz with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 403 due to 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/v1/playlists/5wcnZAy994fsXIesOO3guz</code> from this server.</h2>
<h2></h2>
</body></html>

2025-02-27 17:40:51,848 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/23OIV8qtyNO1lVWzcw6xAk?si=1209092b4b6f439f
2025-02-27 17:40:52,148 - ERROR - HTTP Error for GET to https://api.spotify.com/v1/playlists/23OIV8qtyNO1lVWzcw6xAk with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 403 due to 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/v1/playlists/23OIV8qtyNO1lVWzcw6xAk</code> from this server.</h2>
<h2></h2>
</body></html>

2025-02-27 17:41:17,301 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/23OIV8qtyNO1lVWzcw6xAk?si=1209092b4b6f439f
2025-02-27 17:41:30,523 - INFO - Завершена обработка zxczxczx для 962283941
2025-02-27 17:41:40,754 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/23OIV8qtyNO1lVWzcw6xAk?si=1209092b4b6f439f
2025-02-27 17:41:41,034 - ERROR - HTTP Error for GET to https://api.spotify.com/v1/playlists/23OIV8qtyNO1lVWzcw6xAk with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 403 due to 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/v1/playlists/23OIV8qtyNO1lVWzcw6xAk</code> from this server.</h2>
<h2></h2>
</body></html>

2025-02-27 17:41:46,275 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/23OIV8qtyNO1lVWzcw6xAk?si=1209092b4b6f439f
2025-02-27 17:41:51,570 - ERROR - Ошибка обработки плейлиста для 962283941: HTTPSConnectionPool(host='api.spotify.com', port=443): Read timed out. (read timeout=5)
2025-02-27 17:43:52,263 - INFO - Пользователь 962283941 запустил бота
2025-02-27 17:43:55,777 - INFO - Пользователь 962283941 запросил авторизацию Spotify
2025-02-27 17:44:13,315 - INFO - Пользователь 962283941 успешно авторизовался в Spotify
2025-02-27 17:44:26,693 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/5wcnZAy994fsXIesOO3guz?si=3acec19990a64e40
2025-02-27 17:44:40,061 - INFO - Завершена обработка Cry For Me для 962283941
2025-02-27 17:45:06,270 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/5wcnZAy994fsXIesOO3guz?si=3acec19990a64e40
2025-02-27 17:45:06,554 - ERROR - HTTP Error for GET to https://api.spotify.com/v1/playlists/5wcnZAy994fsXIesOO3guz with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 403 due to 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/v1/playlists/5wcnZAy994fsXIesOO3guz</code> from this server.</h2>
<h2></h2>
</body></html>

2025-02-27 17:47:34,141 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getMe (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000272EB470050>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-27 17:55:17,579 - INFO - Пользователь 962283941 запустил бота
2025-02-27 17:55:38,913 - INFO - Пользователь 962283941 запустил бота
2025-02-27 17:55:41,305 - INFO - Пользователь 962283941 запросил авторизацию Spotify
2025-02-27 17:56:22,569 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/7pPps9b3XciJ7aOOpMK04Y?si=d31bcb0865d442a9
2025-02-27 17:56:43,772 - INFO - Успешно отправлен: Cry For Me для 962283941
2025-02-27 17:56:43,954 - INFO - Завершена обработка Cry For Me для 962283941
2025-02-27 17:57:10,532 - INFO - Пользователь 962283941 выбрал качество 320 kbps через кнопку
2025-02-27 17:57:23,092 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/7pPps9b3XciJ7aOOpMK04Y?si=d31bcb0865d442a9
2025-02-27 17:57:41,427 - INFO - Успешно отправлен: Cry For Me для 962283941
2025-02-27 17:57:41,571 - INFO - Завершена обработка Cry For Me для 962283941
2025-02-27 18:05:16,029 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getUpdates?offset=488892966&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D4E3FC4FD0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-27 18:05:24,389 - INFO - Пользователь 962283941 запустил бота
2025-02-27 18:05:29,150 - INFO - Пользователь 962283941 запросил авторизацию Spotify
2025-02-27 18:05:50,528 - ERROR - Ошибка запуска бота: 'in <string>' requires string as left operand, not int
2025-02-27 18:06:08,552 - INFO - Пользователь 962283941 запросил авторизацию Spotify
2025-02-27 18:06:24,751 - ERROR - Ошибка запуска бота: 'in <string>' requires string as left operand, not int
2025-02-27 18:08:19,490 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/sendMessage?chat_id=962283941&text=%F0%9F%94%97+%D0%9D%D0%B0%D0%B6%D0%BC%D0%B8+%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D1%83+%D0%BD%D0%B8%D0%B6%D0%B5%2C+%D1%87%D1%82%D0%BE%D0%B1%D1%8B+%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C+Spotify.+%D0%9F%D0%BE%D1%81%D0%BB%D0%B5+%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8+%D0%B2%D1%81%D1%82%D0%B0%D0%B2%D1%8C+%D1%81%D1%8E%D0%B4%D0%B0+%D0%BF%D0%BE%D0%BB%D0%BD%D1%8B%D0%B9+URL+%D0%B8%D0%B7+%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B0%21&reply_markup=%7B%22inline_keyboard%22%3A+%5B%5B%7B%22text%22%3A+%22%5Cu041f%5Cu043e%5Cu0434%5Cu043a%5Cu043b%5Cu044e%5Cu0447%5Cu0438%5Cu0442%5Cu044c+Spotify%22%2C+%22url%22%3A+%22https%3A%2F%2Faccounts.spotify.com%2Fauthorize%3Fclient_id%3D905ff1dd336242ebb93b247739dfd08c%26response_type%3Dcode%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A8888%252Fcallback%26scope%3Dplaylist-read-private%2Bplaylist-read-collaborative%2Buser-read-private%2Buser-read-email%22%7D%5D%5D%7D&reply_parameters=%7B%22message_id%22%3A+486%7D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001EC50A8B4D0>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
2025-02-27 18:08:27,524 - INFO - Пользователь 962283941 запустил бота
2025-02-27 18:08:31,738 - INFO - Пользователь 962283941 запросил авторизацию Spotify
2025-02-27 18:08:48,021 - INFO - Пользователь 962283941 успешно авторизовался в Spotify
2025-02-27 18:09:00,195 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/5wcnZAy994fsXIesOO3guz?si=3385c4c2326d48ca
2025-02-27 18:09:00,468 - ERROR - HTTP Error for GET to https://api.spotify.com/v1/playlists/5wcnZAy994fsXIesOO3guz with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 403 due to 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/v1/playlists/5wcnZAy994fsXIesOO3guz</code> from this server.</h2>
<h2></h2>
</body></html>

2025-02-27 18:09:05,444 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/5wcnZAy994fsXIesOO3guz?si=3385c4c2326d48ca
2025-02-27 18:09:05,446 - WARNING - Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000204A66A5E90>: Failed to resolve 'api.spotify.com' ([Errno 11004] getaddrinfo failed)")': /v1/playlists/5wcnZAy994fsXIesOO3guz?additional_types=track
2025-02-27 18:09:06,048 - WARNING - Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000204A66A6CD0>: Failed to resolve 'api.spotify.com' ([Errno 11004] getaddrinfo failed)")': /v1/playlists/5wcnZAy994fsXIesOO3guz?additional_types=track
2025-02-27 18:09:19,694 - INFO - Успешно отправлен: Cry For Me для 962283941
2025-02-27 18:09:19,819 - INFO - Завершена обработка Cry For Me для 962283941
2025-02-27 18:12:22,282 - INFO - Пользователь 962283941 запустил бота
2025-02-27 18:12:26,875 - INFO - Пользователь 962283941 выбрал качество 320 kbps через кнопку
2025-02-27 18:12:35,316 - INFO - Пользователь 962283941 отправил плейлист: https://open.spotify.com/playlist/23OIV8qtyNO1lVWzcw6xAk?si=64a661a003674961
2025-02-27 18:12:46,070 - INFO - Успешно отправлен: snowfall для 962283941
2025-02-27 18:12:59,416 - INFO - Успешно отправлен: Last Christmas для 962283941
2025-02-27 18:12:59,526 - INFO - Завершена обработка zxczxczx для 962283941
2025-02-27 18:18:47,719 - ERROR - Ошибка запуска бота: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7954171512:AAEvKXvSNR39MFZ_6xt4LsbJ_4VXfu6hGmA/getUpdates?offset=488892982&timeout=20 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000204A6670A90>: Failed to resolve 'api.telegram.org' ([Errno 11001] getaddrinfo failed)"))
